# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: FAIR DOs - Findable, Accessible, Interoperable, Reusable Development of Open Simulation 
email: info@scicrunch.org
description: >- # this means to ignore newlines until "baseurl:"
  FAIR DOs (Findable, Accessible, Interoperable, Reusable: Development Of Simulations) is a research education program in the modeling and simulation
  of digestive and renal neurobiology. The main thrust of FAIR DOs is to educate the next generation of researchers and clinicians in the neural
  regulation of digestive and renal epithelia through taught modules and supervised modeling projects that make use of SPARC datasets, maps, and models.
  Overall, FAIR DOs aims to provide about 35/45 hours of training to students, with each student research project producing one publication in the
  Physiome journal--launched by the International Union of Physiological Sciences. The SPARC Portal will provide findability to these student- generated
  open-access models and associated data, as well as accessible interactivity via the O2S2PARC simulation platform. Overall, the FAIR DOs effort will
  provide a unique educational, mentored experience that will also generate a SPARC ecosystem of interoperating models that coherently study the
  neurobiology of digestive and renal epithelial transport. From a didactic “Systems” perspective, this ecosystem of models will be organized to
  follow the teaching narrative of the British Medical Association “Medical Physiology 3rd Ed.” textbook, supplemented with recent literature, setting
  the stage to further leverage SPARC resources for education in the future.
baseurl: /FAIR-DOs/ # the subpath of your site, e.g. /blog
url: https://nih-sparc.github.io # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
remote_theme: pages-themes/slate@v0.2.0
google_analytics: G-DQ580DYGDN

plugins:
  - jekyll-remote-theme # add this line for slate
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
